name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        type: choice
        options:
          - dev
          - test
          - prod

      action:
        description: 'Select Terraform action'
        required: true
        type: choice
        options:
          - init
          - plan
          - apply

      component:
        description: 'Select Terraform component'
        required: true
        type: choice
        options:
          - ec2
          - s3
          - iam
      
      region:
        description: 'Select AWS region'
        required: true
        type: choice
        options:
          - ap-south-1
          - us-east-1
          - eu-west-1

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Show Selected Options
        run: |
          echo "Environment: ${{ inputs.environment }}"
          echo "Action: ${{ inputs.action }}"
          echo "Component: ${{ inputs.component }}"
          echo "AWS Region: ${{ inputs.region }}"